SELECT
FORDEN = pOBJETOS.FCATALOGO_GRUPO
, FORDEN_SEC = pOBJETOS.FCATALOGO_TAG_ORDEN
, FSECTION = pOBJETOS.FCATALOGO_TAG
, FKEY = USUARIO_MENU_PREFS.FOBJETO
, FLABEL = pOBJETOS.FDESCRIPCION
, FHREF = NULL
, FICON = NULL
, FBADGE = '14'
, FBADGE_CLASS = 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-200'
, pOBJETOS.FTS

FROM
USUARIO_MENU_PREFS

INNER JOIN pOBJETOS ON
pOBJETOS.FCODIGO = USUARIO_MENU_PREFS.FOBJETO

WHERE
USUARIO_MENU_PREFS.FUSUARIO = SYSTEM_USER
AND USUARIO_MENU_PREFS.FTIPO = 'HOME'

ORDER BY
pOBJETOS.FCATALOGO_GRUPO
, pOBJETOS.FCATALOGO_TAG_ORDEN
, pOBJETOS.FTS